/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LinkList;

import Emergency.Emergency;
import Employee.Guards;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.security.Timestamp;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Iterator;
import java.util.Locale;
import javax.swing.JComboBox;

/**
 *
 * @author Sean
 */
public class NewJFrame extends javax.swing.JFrame {

    QueueInterfaceV2<Guards> myList = new LinkQueue<Guards>();
    Iterator<Guards> myIterator;
    QueueInterfaceV2<Emergency> emergencyList = new LinkQueue<Emergency>();
    Iterator<Emergency> qIterator;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        //jTextArea1.setEditable(false);
        myList.enqueue(new Guards("Soo", 10));
        myList.enqueue(new Guards("hoo", 20));
        myList.enqueue(new Guards("ken", 30));
        myList.enqueue(new Guards("keith", 30));

        myIterator = myList.getIterator();
        EmergencyMenu.setVisible(false);
        jPanel2.setVisible(false);
        UserMenu.setVisible(false);
        EmergencyMenu.setVisible(false);
        try{
            FileInputStream fileIn = new FileInputStream("user.ser");
            ObjectInputStream in = new ObjectInputStream(fileIn);
            emergencyList.enqueue((Emergency)in.readObject());
            in.close();
            fileIn.close();
            
        }catch(IOException i){
            i.printStackTrace();
        }catch(ClassNotFoundException c ){
            c.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        maintainUsersButton = new javax.swing.JButton();
        EmergencyServiceButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        UserMenu = new javax.swing.JPanel();
        MainPanel = new javax.swing.JPanel();
        AddUserPnl = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        ageTextField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        PanelTwo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        addGuardsBtn = new javax.swing.JButton();
        updateGuardsBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        MainMenu = new javax.swing.JPanel();
        UserBtn = new javax.swing.JButton();
        EmergencyBtn = new javax.swing.JButton();
        EmergencyMenu = new javax.swing.JPanel();
        EmergencyPnl = new javax.swing.JPanel();
        AddEmergency = new javax.swing.JPanel();
        emergencyAdd = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        emergencyNameLbl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        emergencyDescLbl = new javax.swing.JTextArea();
        EmergencyName = new javax.swing.JTextField();
        UpdateEmergency = new javax.swing.JPanel();
        EmergencyCBox = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        EmergencyTxtArea = new javax.swing.JTextArea();
        ServicesPnl = new javax.swing.JPanel();
        BackbtnEmergency = new javax.swing.JButton();
        updateEmergencyBtn = new javax.swing.JButton();
        addEmergencyBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jDialog1.setMinimumSize(new java.awt.Dimension(500, 500));
        jDialog1.setResizable(false);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 748, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );

        maintainUsersButton.setText("Maintain Users");
        maintainUsersButton.setToolTipText("");
        maintainUsersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintainUsersButtonActionPerformed(evt);
            }
        });

        EmergencyServiceButton.setText("Maintain Emergency Service");
        EmergencyServiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmergencyServiceButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Guard and User management System");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(maintainUsersButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EmergencyServiceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(582, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addGap(55, 55, 55)
                .addComponent(maintainUsersButton)
                .addGap(18, 18, 18)
                .addComponent(EmergencyServiceButton)
                .addContainerGap(356, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        MainPanel.setLayout(new java.awt.CardLayout());

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Name:");

        jLabel2.setText("Type:");

        nameTextField.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                nameTextFieldComponentAdded(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Guard", "User" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Age:");

        jButton2.setText("Display Names");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout AddUserPnlLayout = new javax.swing.GroupLayout(AddUserPnl);
        AddUserPnl.setLayout(AddUserPnlLayout);
        AddUserPnlLayout.setHorizontalGroup(
            AddUserPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddUserPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddUserPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddUserPnlLayout.createSequentialGroup()
                        .addGroup(AddUserPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(AddUserPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AddUserPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(222, 222, 222)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddUserPnlLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AddUserPnlLayout.setVerticalGroup(
            AddUserPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddUserPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddUserPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddUserPnlLayout.createSequentialGroup()
                        .addGroup(AddUserPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AddUserPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(AddUserPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(AddUserPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        MainPanel.add(AddUserPnl, "AddUserPnl");

        jLabel5.setText("Emergency Menu");

        javax.swing.GroupLayout PanelTwoLayout = new javax.swing.GroupLayout(PanelTwo);
        PanelTwo.setLayout(PanelTwoLayout);
        PanelTwoLayout.setHorizontalGroup(
            PanelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTwoLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel5)
                .addContainerGap(635, Short.MAX_VALUE))
        );
        PanelTwoLayout.setVerticalGroup(
            PanelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTwoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addContainerGap(317, Short.MAX_VALUE))
        );

        MainPanel.add(PanelTwo, "PanelTwo");

        addGuardsBtn.setText("Add Users");
        addGuardsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGuardsBtnActionPerformed(evt);
            }
        });

        updateGuardsBtn.setText("Update Users");
        updateGuardsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateGuardsBtnActionPerformed(evt);
            }
        });

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UserMenuLayout = new javax.swing.GroupLayout(UserMenu);
        UserMenu.setLayout(UserMenuLayout);
        UserMenuLayout.setHorizontalGroup(
            UserMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserMenuLayout.createSequentialGroup()
                .addContainerGap(546, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addGap(18, 18, 18)
                .addComponent(updateGuardsBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addGuardsBtn)
                .addContainerGap())
            .addGroup(UserMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(UserMenuLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        UserMenuLayout.setVerticalGroup(
            UserMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UserMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addGuardsBtn)
                    .addComponent(updateGuardsBtn)
                    .addComponent(backBtn))
                .addContainerGap(384, Short.MAX_VALUE))
            .addGroup(UserMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserMenuLayout.createSequentialGroup()
                    .addContainerGap(46, Short.MAX_VALUE)
                    .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        UserBtn.setText("Manage Users");
        UserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserBtnActionPerformed(evt);
            }
        });

        EmergencyBtn.setText("Manage Emergency");
        EmergencyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmergencyBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainMenuLayout = new javax.swing.GroupLayout(MainMenu);
        MainMenu.setLayout(MainMenuLayout);
        MainMenuLayout.setHorizontalGroup(
            MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainMenuLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmergencyBtn)
                    .addComponent(UserBtn))
                .addContainerGap(645, Short.MAX_VALUE))
        );
        MainMenuLayout.setVerticalGroup(
            MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainMenuLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(UserBtn)
                .addGap(18, 18, 18)
                .addComponent(EmergencyBtn)
                .addContainerGap(315, Short.MAX_VALUE))
        );

        EmergencyMenu.setPreferredSize(new java.awt.Dimension(804, 418));

        EmergencyPnl.setLayout(new java.awt.CardLayout());

        emergencyAdd.setText("Add");
        emergencyAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emergencyAddActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Add New Emergency");

        emergencyNameLbl.setText("Emergency Name :");

        jLabel8.setText("Emergency Description:");

        emergencyDescLbl.setColumns(20);
        emergencyDescLbl.setRows(5);
        jScrollPane2.setViewportView(emergencyDescLbl);

        javax.swing.GroupLayout AddEmergencyLayout = new javax.swing.GroupLayout(AddEmergency);
        AddEmergency.setLayout(AddEmergencyLayout);
        AddEmergencyLayout.setHorizontalGroup(
            AddEmergencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddEmergencyLayout.createSequentialGroup()
                .addGroup(AddEmergencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddEmergencyLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(emergencyAdd))
                    .addGroup(AddEmergencyLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(AddEmergencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(AddEmergencyLayout.createSequentialGroup()
                                .addGroup(AddEmergencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(emergencyNameLbl)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(AddEmergencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2)
                                    .addComponent(EmergencyName))))))
                .addContainerGap(438, Short.MAX_VALUE))
        );
        AddEmergencyLayout.setVerticalGroup(
            AddEmergencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddEmergencyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(AddEmergencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emergencyNameLbl)
                    .addComponent(EmergencyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddEmergencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(emergencyAdd)
                .addGap(46, 46, 46))
        );

        EmergencyPnl.add(AddEmergency, "AddEmergency");

        EmergencyCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmergencyCBoxActionPerformed(evt);
            }
        });

        EmergencyTxtArea.setEditable(false);
        EmergencyTxtArea.setColumns(20);
        EmergencyTxtArea.setRows(5);
        jScrollPane3.setViewportView(EmergencyTxtArea);

        javax.swing.GroupLayout UpdateEmergencyLayout = new javax.swing.GroupLayout(UpdateEmergency);
        UpdateEmergency.setLayout(UpdateEmergencyLayout);
        UpdateEmergencyLayout.setHorizontalGroup(
            UpdateEmergencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateEmergencyLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(EmergencyCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(461, Short.MAX_VALUE))
        );
        UpdateEmergencyLayout.setVerticalGroup(
            UpdateEmergencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateEmergencyLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(UpdateEmergencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmergencyCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        EmergencyPnl.add(UpdateEmergency, "UpdateEmergency");

        javax.swing.GroupLayout ServicesPnlLayout = new javax.swing.GroupLayout(ServicesPnl);
        ServicesPnl.setLayout(ServicesPnlLayout);
        ServicesPnlLayout.setHorizontalGroup(
            ServicesPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 784, Short.MAX_VALUE)
        );
        ServicesPnlLayout.setVerticalGroup(
            ServicesPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 363, Short.MAX_VALUE)
        );

        EmergencyPnl.add(ServicesPnl, "RequestServices");

        BackbtnEmergency.setText("Back");
        BackbtnEmergency.setToolTipText("");
        BackbtnEmergency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnEmergencyActionPerformed(evt);
            }
        });

        updateEmergencyBtn.setText("Update Emergency");
        updateEmergencyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEmergencyBtnActionPerformed(evt);
            }
        });

        addEmergencyBtn.setText("Add Emergency");
        addEmergencyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmergencyBtnActionPerformed(evt);
            }
        });

        jButton3.setText("Request Service");

        javax.swing.GroupLayout EmergencyMenuLayout = new javax.swing.GroupLayout(EmergencyMenu);
        EmergencyMenu.setLayout(EmergencyMenuLayout);
        EmergencyMenuLayout.setHorizontalGroup(
            EmergencyMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmergencyMenuLayout.createSequentialGroup()
                .addGroup(EmergencyMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(EmergencyMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(EmergencyPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(EmergencyMenuLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(BackbtnEmergency)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(addEmergencyBtn)
                        .addGap(18, 18, 18)
                        .addComponent(updateEmergencyBtn)))
                .addContainerGap())
        );
        EmergencyMenuLayout.setVerticalGroup(
            EmergencyMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmergencyMenuLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(EmergencyMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackbtnEmergency)
                    .addComponent(updateEmergencyBtn)
                    .addComponent(addEmergencyBtn)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmergencyPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UserMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(19, Short.MAX_VALUE)
                    .addComponent(MainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(EmergencyMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UserMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(MainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(EmergencyMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void maintainUsersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintainUsersButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maintainUsersButtonActionPerformed

    private void EmergencyServiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmergencyServiceButtonActionPerformed
        // TODO add your handling code here:
        EmergencyMenu.setVisible(true);

    }//GEN-LAST:event_EmergencyServiceButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String toDisplay = "";

        while (myIterator.hasNext()) {
            toDisplay += myIterator.next().getName() + "\n";
            myIterator.remove();
        }
        jTextArea1.setText(toDisplay);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void nameTextFieldComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_nameTextFieldComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldComponentAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        myList.enqueue(new Guards(nameTextField.getText(), Integer.parseInt(ageTextField.getText())));
        myIterator = myList.getIterator();
        jComboBox2.getSelectedItem();

        //jDialog1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void updateGuardsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateGuardsBtnActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) MainPanel.getLayout();
        card.show(MainPanel, "PanelTwo");

    }//GEN-LAST:event_updateGuardsBtnActionPerformed

    private void addGuardsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGuardsBtnActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) MainPanel.getLayout();
        card.show(MainPanel, "AddUserPnl");
    }//GEN-LAST:event_addGuardsBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        UserMenu.setVisible(false);
        MainMenu.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void UserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserBtnActionPerformed
        // TODO add your handling code here:
        UserMenu.setVisible(true);
        MainMenu.setVisible(false);
    }//GEN-LAST:event_UserBtnActionPerformed

    private void EmergencyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmergencyBtnActionPerformed
        // TODO add your handling code here:
        EmergencyMenu.setVisible(true);
        MainMenu.setVisible(false);
    }//GEN-LAST:event_EmergencyBtnActionPerformed

    private void emergencyAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emergencyAddActionPerformed
        // TODO add your handling code here:

        emergencyList.enqueue(new Emergency(EmergencyName.getText(), emergencyDescLbl.getText(), ZonedDateTime.now()));
        EmergencyCBox.addItem(emergencyList.getFront().getName());
//        qIterator = emergencyList.getIterator();
//        String toDisplay = "";
//         while (qIterator.hasNext()) {
//            toDisplay += qIterator.next().getName() + "\n";
//            qIterator.remove();
//        }
    }//GEN-LAST:event_emergencyAddActionPerformed

    private void BackbtnEmergencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnEmergencyActionPerformed
        // TODO add your handling code here:
        EmergencyMenu.setVisible(false);
        MainMenu.setVisible(true);
    }//GEN-LAST:event_BackbtnEmergencyActionPerformed

    private void addEmergencyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmergencyBtnActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) EmergencyPnl.getLayout();
        card.show(EmergencyPnl, "AddEmergency");

    }//GEN-LAST:event_addEmergencyBtnActionPerformed

    private void updateEmergencyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEmergencyBtnActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) EmergencyPnl.getLayout();
        card.show(EmergencyPnl, "UpdateEmergency");

    }//GEN-LAST:event_updateEmergencyBtnActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void EmergencyCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmergencyCBoxActionPerformed
        // TODO add your handling code here:
        Emergency temp = null;
        String toDisplay = "";
        if (!emergencyList.isEmpty()) {
            qIterator = emergencyList.getIterator();
            while (qIterator.hasNext()) {
                temp = qIterator.next();
                if (EmergencyCBox.getSelectedItem().toString().equals(temp.getName())) {
                    toDisplay += temp.toString();
                }
                qIterator.remove();
            }
            EmergencyTxtArea.setText(toDisplay);
        }


    }//GEN-LAST:event_EmergencyCBoxActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
           try {
            FileOutputStream fileOut = new FileOutputStream("user.ser");
            ObjectOutputStream out = new ObjectOutputStream(fileOut);
            out.writeObject(emergencyList.getFront());
            out.close();
            fileOut.close();
            
        } catch (IOException i) {
            i.printStackTrace();
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddEmergency;
    private javax.swing.JPanel AddUserPnl;
    private javax.swing.JButton BackbtnEmergency;
    private javax.swing.JButton EmergencyBtn;
    private javax.swing.JComboBox<String> EmergencyCBox;
    private javax.swing.JPanel EmergencyMenu;
    private javax.swing.JTextField EmergencyName;
    private javax.swing.JPanel EmergencyPnl;
    private javax.swing.JButton EmergencyServiceButton;
    private javax.swing.JTextArea EmergencyTxtArea;
    private javax.swing.JPanel MainMenu;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel PanelTwo;
    private javax.swing.JPanel ServicesPnl;
    private javax.swing.JPanel UpdateEmergency;
    private javax.swing.JButton UserBtn;
    private javax.swing.JPanel UserMenu;
    private javax.swing.JButton addEmergencyBtn;
    private javax.swing.JButton addGuardsBtn;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton emergencyAdd;
    private javax.swing.JTextArea emergencyDescLbl;
    private javax.swing.JLabel emergencyNameLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton maintainUsersButton;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton updateEmergencyBtn;
    private javax.swing.JButton updateGuardsBtn;
    // End of variables declaration//GEN-END:variables
}
