/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LinkList;

import Interfaces.QueueInterfaceV2;
import Interfaces.ListIteratorInterface;
import Emergency.Emergency;
import Interfaces.NameInterface;
import Employee.Guards;
import java.awt.CardLayout;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.time.ZonedDateTime;
import java.util.Iterator;
import javax.swing.JComboBox;
import javax.swing.JTextArea;

/**
 *
 * @author Sean
 */
public class NewJFrame extends javax.swing.JFrame {
    
    QueueInterfaceV2<Guards> myList = new LinkQueue<>();
    Iterator<Guards> myIterator;

    //Emergency list
    Iterator<Emergency> listIterator;
    ListIteratorInterface<Emergency> LEmergency = new LinkList<>();

    //Service
    QueueInterfaceV2<Emergency> QEmergency = new LinkQueue<>();

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        //jTextArea1.setEditable(false);
        myList.enqueue(new Guards("Soo", 10));
        myList.enqueue(new Guards("hoo", 20));
        myList.enqueue(new Guards("ken", 30));
        myList.enqueue(new Guards("keith", 30));
        
        myIterator = myList.getIterator();
        EmergencyMenu.setVisible(false);
        jPanel2.setVisible(false);
        UserMenu.setVisible(false);
        EmergencyMenu.setVisible(false);
        
        try {           //creating storing in file
            FileInputStream fileIn = new FileInputStream("Emergency.ser");
            ObjectInputStream in = new ObjectInputStream(fileIn);
            LEmergency = (ListIteratorInterface<Emergency>) in.readObject();
            
            in.close();
            fileIn.close();
            listIterator = LEmergency.getIterator();
            int highestID = 0;
            Emergency temp;
            while (listIterator.hasNext()) {
                temp = listIterator.next();
//                EmergencyCBox.insertItemAt(temp.getName(),count);

                if (temp.getID() > highestID) {
                    highestID = temp.getID();
                }
                listIterator.remove();
                
            }
            LEmergency.getEntry(0).setTotalEmergency(highestID);
            
            System.out.println(LEmergency.getEntry(0).getTotalEmergency());
        } catch (IOException i) {
            i.printStackTrace();
        } catch (ClassNotFoundException c) {
            c.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        maintainUsersButton = new javax.swing.JButton();
        EmergencyServiceButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        UserMenu = new javax.swing.JPanel();
        MainPanel = new javax.swing.JPanel();
        AddUserPnl = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        ageTextField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        PanelTwo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        addGuardsBtn = new javax.swing.JButton();
        updateGuardsBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        MainMenu = new javax.swing.JPanel();
        UserBtn = new javax.swing.JButton();
        EmergencyBtn = new javax.swing.JButton();
        EmergencyMenu = new javax.swing.JPanel();
        EmergencyPnl = new javax.swing.JPanel();
        AddEmergency = new javax.swing.JPanel();
        emergencyAdd = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        emergencyNameLbl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        emergencyDescLbl = new javax.swing.JTextArea();
        EmergencyTypeCbox = new javax.swing.JComboBox<>();
        UpdateEmergency = new javax.swing.JPanel();
        EmergencyCBox = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        CEmergencyTextArea = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        CEmergencyDetailsTxtArea = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        IDCbox = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        ServicesPnl = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        EmergencyTxtArea = new javax.swing.JTextArea();
        OngoingELbl = new javax.swing.JLabel();
        getRequestBtn = new javax.swing.JButton();
        HandleQBtn = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        QDetailsTxtArea = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        BackbtnEmergency = new javax.swing.JButton();
        updateEmergencyBtn = new javax.swing.JButton();
        addEmergencyBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jDialog1.setMinimumSize(new java.awt.Dimension(500, 500));
        jDialog1.setResizable(false);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 748, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );

        maintainUsersButton.setText("Maintain Users");
        maintainUsersButton.setToolTipText("");
        maintainUsersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintainUsersButtonActionPerformed(evt);
            }
        });

        EmergencyServiceButton.setText("Maintain Emergency Service");
        EmergencyServiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmergencyServiceButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Guard and User management System");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(maintainUsersButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EmergencyServiceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(582, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addGap(55, 55, 55)
                .addComponent(maintainUsersButton)
                .addGap(18, 18, 18)
                .addComponent(EmergencyServiceButton)
                .addContainerGap(356, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        MainPanel.setLayout(new java.awt.CardLayout());

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Name:");

        jLabel2.setText("Type:");

        nameTextField.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                nameTextFieldComponentAdded(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Guard", "User" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Age:");

        jButton2.setText("Display Names");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout AddUserPnlLayout = new javax.swing.GroupLayout(AddUserPnl);
        AddUserPnl.setLayout(AddUserPnlLayout);
        AddUserPnlLayout.setHorizontalGroup(
            AddUserPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddUserPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddUserPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddUserPnlLayout.createSequentialGroup()
                        .addGroup(AddUserPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(AddUserPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AddUserPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(222, 222, 222)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddUserPnlLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AddUserPnlLayout.setVerticalGroup(
            AddUserPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddUserPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddUserPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddUserPnlLayout.createSequentialGroup()
                        .addGroup(AddUserPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AddUserPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(AddUserPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(AddUserPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        MainPanel.add(AddUserPnl, "AddUserPnl");

        jLabel5.setText("Emergency Menu");

        javax.swing.GroupLayout PanelTwoLayout = new javax.swing.GroupLayout(PanelTwo);
        PanelTwo.setLayout(PanelTwoLayout);
        PanelTwoLayout.setHorizontalGroup(
            PanelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTwoLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel5)
                .addContainerGap(635, Short.MAX_VALUE))
        );
        PanelTwoLayout.setVerticalGroup(
            PanelTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTwoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addContainerGap(317, Short.MAX_VALUE))
        );

        MainPanel.add(PanelTwo, "PanelTwo");

        addGuardsBtn.setText("Add Users");
        addGuardsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGuardsBtnActionPerformed(evt);
            }
        });

        updateGuardsBtn.setText("Update Users");
        updateGuardsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateGuardsBtnActionPerformed(evt);
            }
        });

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UserMenuLayout = new javax.swing.GroupLayout(UserMenu);
        UserMenu.setLayout(UserMenuLayout);
        UserMenuLayout.setHorizontalGroup(
            UserMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserMenuLayout.createSequentialGroup()
                .addContainerGap(546, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addGap(18, 18, 18)
                .addComponent(updateGuardsBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addGuardsBtn)
                .addContainerGap())
            .addGroup(UserMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(UserMenuLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        UserMenuLayout.setVerticalGroup(
            UserMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UserMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addGuardsBtn)
                    .addComponent(updateGuardsBtn)
                    .addComponent(backBtn))
                .addContainerGap(384, Short.MAX_VALUE))
            .addGroup(UserMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserMenuLayout.createSequentialGroup()
                    .addContainerGap(46, Short.MAX_VALUE)
                    .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        UserBtn.setText("Manage Users");
        UserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserBtnActionPerformed(evt);
            }
        });

        EmergencyBtn.setText("Manage Emergency");
        EmergencyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmergencyBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainMenuLayout = new javax.swing.GroupLayout(MainMenu);
        MainMenu.setLayout(MainMenuLayout);
        MainMenuLayout.setHorizontalGroup(
            MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainMenuLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmergencyBtn)
                    .addComponent(UserBtn))
                .addContainerGap(645, Short.MAX_VALUE))
        );
        MainMenuLayout.setVerticalGroup(
            MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainMenuLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(UserBtn)
                .addGap(18, 18, 18)
                .addComponent(EmergencyBtn)
                .addContainerGap(315, Short.MAX_VALUE))
        );

        EmergencyMenu.setPreferredSize(new java.awt.Dimension(804, 418));

        EmergencyPnl.setLayout(new java.awt.CardLayout());

        emergencyAdd.setText("Add");
        emergencyAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emergencyAddActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Add New Emergency");

        emergencyNameLbl.setText("Emergency Type :");

        jLabel8.setText("Emergency Description:");

        emergencyDescLbl.setColumns(20);
        emergencyDescLbl.setRows(5);
        jScrollPane2.setViewportView(emergencyDescLbl);

        EmergencyTypeCbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Life Threatening/Fire", "Theft", "Facility Maintenance", "Room Services" }));

        javax.swing.GroupLayout AddEmergencyLayout = new javax.swing.GroupLayout(AddEmergency);
        AddEmergency.setLayout(AddEmergencyLayout);
        AddEmergencyLayout.setHorizontalGroup(
            AddEmergencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddEmergencyLayout.createSequentialGroup()
                .addGroup(AddEmergencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddEmergencyLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(emergencyAdd))
                    .addGroup(AddEmergencyLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(AddEmergencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(AddEmergencyLayout.createSequentialGroup()
                                .addGroup(AddEmergencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(emergencyNameLbl)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(AddEmergencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EmergencyTypeCbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(438, Short.MAX_VALUE))
        );
        AddEmergencyLayout.setVerticalGroup(
            AddEmergencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddEmergencyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(AddEmergencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emergencyNameLbl)
                    .addComponent(EmergencyTypeCbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddEmergencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(emergencyAdd)
                .addGap(46, 46, 46))
        );

        EmergencyPnl.add(AddEmergency, "AddEmergency");

        EmergencyCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Life Threatening/Fire", "Theft", "Facility Maintenance", "Room Services" }));
        EmergencyCBox.setToolTipText("");
        EmergencyCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmergencyCBoxActionPerformed(evt);
            }
        });

        CEmergencyTextArea.setEditable(false);
        CEmergencyTextArea.setColumns(20);
        CEmergencyTextArea.setRows(5);
        jScrollPane3.setViewportView(CEmergencyTextArea);

        jLabel7.setText("View Completed Emergency");

        jLabel9.setText("Completed Emergency List:");

        CEmergencyDetailsTxtArea.setEditable(false);
        CEmergencyDetailsTxtArea.setColumns(20);
        CEmergencyDetailsTxtArea.setRows(5);
        jScrollPane6.setViewportView(CEmergencyDetailsTxtArea);

        jLabel11.setText("Details");

        IDCbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDCboxActionPerformed(evt);
            }
        });

        jLabel12.setText("ID:");

        javax.swing.GroupLayout UpdateEmergencyLayout = new javax.swing.GroupLayout(UpdateEmergency);
        UpdateEmergency.setLayout(UpdateEmergencyLayout);
        UpdateEmergencyLayout.setHorizontalGroup(
            UpdateEmergencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateEmergencyLayout.createSequentialGroup()
                .addGroup(UpdateEmergencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdateEmergencyLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(UpdateEmergencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(UpdateEmergencyLayout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IDCbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(UpdateEmergencyLayout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jLabel7))))
                    .addGroup(UpdateEmergencyLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(EmergencyCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                .addGroup(UpdateEmergencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97))
        );
        UpdateEmergencyLayout.setVerticalGroup(
            UpdateEmergencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateEmergencyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(4, 4, 4)
                .addGroup(UpdateEmergencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(UpdateEmergencyLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(UpdateEmergencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmergencyCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(UpdateEmergencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(UpdateEmergencyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(IDCbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12)))))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        EmergencyPnl.add(UpdateEmergency, "UpdateEmergency");

        EmergencyTxtArea.setEditable(false);
        EmergencyTxtArea.setColumns(20);
        EmergencyTxtArea.setRows(5);
        jScrollPane4.setViewportView(EmergencyTxtArea);

        OngoingELbl.setText("Ongoing Emergency");

        getRequestBtn.setText("Get Request");
        getRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getRequestBtnActionPerformed(evt);
            }
        });

        HandleQBtn.setText("Handle Queue");
        HandleQBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HandleQBtnActionPerformed(evt);
            }
        });

        QDetailsTxtArea.setEditable(false);
        QDetailsTxtArea.setColumns(20);
        QDetailsTxtArea.setRows(5);
        jScrollPane5.setViewportView(QDetailsTxtArea);

        jLabel10.setText("Details");

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ServicesPnlLayout = new javax.swing.GroupLayout(ServicesPnl);
        ServicesPnl.setLayout(ServicesPnlLayout);
        ServicesPnlLayout.setHorizontalGroup(
            ServicesPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ServicesPnlLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(ServicesPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ServicesPnlLayout.createSequentialGroup()
                        .addComponent(getRequestBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(HandleQBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addGroup(ServicesPnlLayout.createSequentialGroup()
                        .addGroup(ServicesPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OngoingELbl))
                        .addGap(109, 109, 109)
                        .addGroup(ServicesPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(296, Short.MAX_VALUE))
        );
        ServicesPnlLayout.setVerticalGroup(
            ServicesPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ServicesPnlLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(ServicesPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OngoingELbl)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ServicesPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ServicesPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getRequestBtn)
                    .addComponent(HandleQBtn)
                    .addComponent(jButton4))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        EmergencyPnl.add(ServicesPnl, "RequestServices");

        BackbtnEmergency.setText("Back");
        BackbtnEmergency.setToolTipText("");
        BackbtnEmergency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnEmergencyActionPerformed(evt);
            }
        });

        updateEmergencyBtn.setText("History");
        updateEmergencyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEmergencyBtnActionPerformed(evt);
            }
        });

        addEmergencyBtn.setText("Add Emergency");
        addEmergencyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmergencyBtnActionPerformed(evt);
            }
        });

        jButton3.setText("Emergency and Services");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EmergencyMenuLayout = new javax.swing.GroupLayout(EmergencyMenu);
        EmergencyMenu.setLayout(EmergencyMenuLayout);
        EmergencyMenuLayout.setHorizontalGroup(
            EmergencyMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmergencyMenuLayout.createSequentialGroup()
                .addGroup(EmergencyMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(EmergencyMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(EmergencyPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(EmergencyMenuLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(BackbtnEmergency)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(addEmergencyBtn)
                        .addGap(18, 18, 18)
                        .addComponent(updateEmergencyBtn)))
                .addContainerGap())
        );
        EmergencyMenuLayout.setVerticalGroup(
            EmergencyMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmergencyMenuLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(EmergencyMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackbtnEmergency)
                    .addComponent(updateEmergencyBtn)
                    .addComponent(addEmergencyBtn)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmergencyPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UserMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(19, Short.MAX_VALUE)
                    .addComponent(MainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(EmergencyMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UserMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(MainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(EmergencyMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String toDisplay = "";
        
        while (myIterator.hasNext()) {
            toDisplay += myIterator.next().getName() + "\n";
            myIterator.remove();
        }
        jTextArea1.setText(toDisplay);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void nameTextFieldComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_nameTextFieldComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldComponentAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        myList.enqueue(new Guards(nameTextField.getText(), Integer.parseInt(ageTextField.getText())));
        myIterator = myList.getIterator();
        jComboBox2.getSelectedItem();

        //jDialog1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void updateGuardsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateGuardsBtnActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) MainPanel.getLayout();
        card.show(MainPanel, "PanelTwo");

    }//GEN-LAST:event_updateGuardsBtnActionPerformed

    private void addGuardsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGuardsBtnActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) MainPanel.getLayout();
        card.show(MainPanel, "AddUserPnl");
    }//GEN-LAST:event_addGuardsBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        UserMenu.setVisible(false);
        MainMenu.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void UserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserBtnActionPerformed
        // TODO add your handling code here:
        UserMenu.setVisible(true);
        MainMenu.setVisible(false);
    }//GEN-LAST:event_UserBtnActionPerformed

    private void EmergencyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmergencyBtnActionPerformed
        // TODO add your handling code here:
        EmergencyMenu.setVisible(true);
        MainMenu.setVisible(false);
    }//GEN-LAST:event_EmergencyBtnActionPerformed

    private void emergencyAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emergencyAddActionPerformed
        // TODO add your handling code here:
        Emergency temp = new Emergency(EmergencyTypeCbox.getSelectedItem().toString(), emergencyDescLbl.getText(), ZonedDateTime.now(), EmergencyTypeCbox.getSelectedIndex());
        QEmergency.enqueue(temp);
//        LEmergency.add(temp);
//        int i =0;
//        while(!temp.getName().equals(EmergencyCBox.getItemAt(i))&& i <= EmergencyCBox.getItemCount()){
//        EmergencyCBox.addItem(temp.getName());
//        if(EmergencyCBox.getItemCount() == 1){
//            break;
//        }
//        
//        i++;
//        }
//        qIterator = emergencyList.getIterator();
//        String toDisplay = "";
//         while (qIterator.hasNext()) {
//            toDisplay += qIterator.next().getName() + "\n";
//            qIterator.remove();
//        }
    }//GEN-LAST:event_emergencyAddActionPerformed

    private void BackbtnEmergencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnEmergencyActionPerformed
        // TODO add your handling code here:
        EmergencyMenu.setVisible(false);
        MainMenu.setVisible(true);
    }//GEN-LAST:event_BackbtnEmergencyActionPerformed

    private void addEmergencyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmergencyBtnActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) EmergencyPnl.getLayout();
        card.show(EmergencyPnl, "AddEmergency");

    }//GEN-LAST:event_addEmergencyBtnActionPerformed

    private void updateEmergencyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEmergencyBtnActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) EmergencyPnl.getLayout();
        card.show(EmergencyPnl, "UpdateEmergency");
        

    }//GEN-LAST:event_updateEmergencyBtnActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void EmergencyCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmergencyCBoxActionPerformed
        // TODO add your handling code here:
        CEmergencyDetailsTxtArea.setText("");
        displayListToTxtArea(LEmergency, listIterator, EmergencyCBox, CEmergencyTextArea, true);
        Iterator itr = LEmergency.getIterator();
        IDCbox.removeAllItems();
        Emergency temp;
        int count = 0;
        while (itr.hasNext()) {
            temp = (Emergency) itr.next();
            if (EmergencyCBox.getSelectedItem().toString().equals(temp.getName())) {
                IDCbox.addItem(Integer.toString(temp.getID()));
            }
            itr.remove();
        }

    }//GEN-LAST:event_EmergencyCBoxActionPerformed
    //displays to textarea acccording to which was selected in the combo box

    public void displayListToTxtArea(ListIteratorInterface list, Iterator itr, JComboBox box, JTextArea txtArea, boolean displayNameOnly) {
        NameInterface obj;
        String toDisplay = "";
        int count = 1;
        if (!list.isEmpty()) {
            itr = list.getIterator();
            while (itr.hasNext()) {
                obj = (NameInterface) itr.next();
                if (box.getSelectedItem().toString().equals(obj.getName()) || box.getSelectedItem().toString().equals(Integer.toString(obj.getID()))) {
                    toDisplay += count++ + ".";
                    if (displayNameOnly) {
                        toDisplay += obj.getName();
                        toDisplay += "\nID: " + obj.getID();
                        toDisplay += "\n";
                    } else {
                        toDisplay += obj.toString();
                    }
                }
                
                itr.remove();
            }
            txtArea.setText(toDisplay);
            
        }
        
    }
    
    public void displayQueueToTxtArea(QueueInterfaceV2 queue, Iterator itr, JTextArea txtArea) {
        NameInterface obj;
        String toDisplay = "";
        int count = 1;
        if (!queue.isEmpty()) {
            itr = queue.getIterator();
            while (itr.hasNext()) {
                obj = (NameInterface) itr.next();
                toDisplay += count++ + ".";
                toDisplay += obj.getName();
                toDisplay += "\n";
                
                itr.remove();
            }
            txtArea.setText(toDisplay);
            
        }
        
    }

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        try {
            FileOutputStream fileOut = new FileOutputStream("Emergency.ser");
            ObjectOutputStream out = new ObjectOutputStream(fileOut);
            out.writeObject(LEmergency);
            out.close();
            fileOut.close();
            
        } catch (IOException i) {
            i.printStackTrace();
        }
    }//GEN-LAST:event_formWindowClosing

    private void EmergencyServiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmergencyServiceButtonActionPerformed
        // TODO add your handling code here:
        EmergencyMenu.setVisible(true);
    }//GEN-LAST:event_EmergencyServiceButtonActionPerformed

    private void maintainUsersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintainUsersButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maintainUsersButtonActionPerformed

    private void getRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getRequestBtnActionPerformed
        // TODO add your handling code here:
        displayQueueToTxtArea(QEmergency, myIterator, EmergencyTxtArea);
    }//GEN-LAST:event_getRequestBtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) EmergencyPnl.getLayout();
        card.show(EmergencyPnl, "RequestServices");
        displayQueueToTxtArea(QEmergency, myIterator, EmergencyTxtArea);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void HandleQBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HandleQBtnActionPerformed
        // TODO add your handling code here:
        Emergency temp = QEmergency.getFront();
        
        QDetailsTxtArea.setText(temp.toString());
        if (!QEmergency.isEmpty()) {
            displayQueueToTxtArea(QEmergency, myIterator, EmergencyTxtArea);
        } else {
            EmergencyTxtArea.setText("");
        }
    }//GEN-LAST:event_HandleQBtnActionPerformed

    private void IDCboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDCboxActionPerformed
        // TODO add your handling code here:
        if (IDCbox.getItemCount() > 0) {
            displayListToTxtArea(LEmergency, listIterator, IDCbox, CEmergencyDetailsTxtArea, false);
        }

    }//GEN-LAST:event_IDCboxActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (!EmergencyTxtArea.getText().equals("")) {
            Emergency temp = QEmergency.dequeue();
            temp.setStatus(true);
            LEmergency.add(temp);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddEmergency;
    private javax.swing.JPanel AddUserPnl;
    private javax.swing.JButton BackbtnEmergency;
    private javax.swing.JTextArea CEmergencyDetailsTxtArea;
    private javax.swing.JTextArea CEmergencyTextArea;
    private javax.swing.JButton EmergencyBtn;
    private javax.swing.JComboBox<String> EmergencyCBox;
    private javax.swing.JPanel EmergencyMenu;
    private javax.swing.JPanel EmergencyPnl;
    private javax.swing.JButton EmergencyServiceButton;
    private javax.swing.JTextArea EmergencyTxtArea;
    private javax.swing.JComboBox<String> EmergencyTypeCbox;
    private javax.swing.JButton HandleQBtn;
    private javax.swing.JComboBox<String> IDCbox;
    private javax.swing.JPanel MainMenu;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel OngoingELbl;
    private javax.swing.JPanel PanelTwo;
    private javax.swing.JTextArea QDetailsTxtArea;
    private javax.swing.JPanel ServicesPnl;
    private javax.swing.JPanel UpdateEmergency;
    private javax.swing.JButton UserBtn;
    private javax.swing.JPanel UserMenu;
    private javax.swing.JButton addEmergencyBtn;
    private javax.swing.JButton addGuardsBtn;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton emergencyAdd;
    private javax.swing.JTextArea emergencyDescLbl;
    private javax.swing.JLabel emergencyNameLbl;
    private javax.swing.JButton getRequestBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton maintainUsersButton;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton updateEmergencyBtn;
    private javax.swing.JButton updateGuardsBtn;
    // End of variables declaration//GEN-END:variables
}
